export enum ExceptionMessageEnum {
    USER_NOT_FOUND = 'User Not Found',
    USER_WRONG_CREDENTIALS = 'Wrong credentials',
    USER_REGISTRATION_ERROR = 'Unsuccessfully User registration',
    USER_REGISTRATION_PASSWORD_NOT_MATCH = "Passwords doesn't match",
    USER_EXIST = 'User already exists',
    WRONG_PASSWORD_ERROR = 'Wrong password',
    FIT_PASS_USER_NOT_FOUND = 'Fit Pass User Not Found',
    FIT_PASS_USER_UPDATE_ERROR = 'Unsuccessfully Fit Pass User update',
    FIT_PASS_USER_DELETE_ERROR = 'Unsuccessfully Fit Pass User delete',
    FAMILY_MEMBER_NOT_FOUND = 'Fit Pass Family Member Not Found',
    FAMILY_MEMBER_UPDATE_ERROR = 'Unsuccessfully Family Member update',
    EMAIL_ALREADY_EXIST = 'Email already exist',
    CARD_NOT_FOUND = 'Card Not Found',
    CARD_UPDATE_ERROR = 'Unsuccessfully card update',
    CARD_DELETE_ERROR = 'Unsuccessfully card delete',
    CARD_NUMBER_ERROR = 'Card number is already exist',
    FIT_PASS_USER_HISTORY_NOT_FOUND = 'Fit Pass User History Not Found',
    FIT_PASS_USER_HISTORY_ALREADY_ACTIVE = 'Fit Pass User is already active',
    FAMILY_MEMBER_HISTORY_NOT_FOUND = 'Payment History not found',
    FAMILY_MEMBER_HISTORY_DELETE_ERROR = 'Unsuccessfully payment history delete',
    FAMILY_MEMBER_PAYMENT_NOT_PAID = 'Family member have debt, cannot be deleted',
    FIT_PASS_USER_DOESNT_HAVE_CARD = 'Fit Pass User does not have a card',
  }